# Generated by Django 5.1.7 on 2025-03-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('SCOLARITE', 'Responsable de scolarité'), ('ENSEIGNANT', 'Enseignant'), ('ETUDIANT', 'Étudiant'), ('teacher', 'Enseignant')], default='ETUDIANT', max_length=20),
        ),
    ]
